# General informations
version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    formatter: "standard"
    class: "logging.StreamHandler"
    stream: "ext://sys.stdout"

  extraction:
    formatter: "standard"
    class: "logging.FileHandler"
    filename: "logs/extraction.log"

  processing:
    formatter: "standard"
    class: "logging.FileHandler"
    filename: "logs/processing.log"

  #  Handler for Machine Learning Experiments
  benchmarking:
    formatter: "standard"
    class: "logging.FileHandler"
    filename: "logs/benchmarking.log"

loggers:
  # This catches everything inside pipe_bci_toolkit.data
  pipe_bci_toolkit.data:
    handlers: ["extraction"]
    level: "DEBUG"
    propagate: true
  
  # This catches everything inside pipe_bci_toolkit.processing
  pipe_bci_toolkit.processing: 
    handlers: ["processing"]
    level: "DEBUG"
    propagate: true

  # This catches everything inside pipe_bci_toolkit.tracking
  pipe_bci_toolkit.tracking:
    handlers: ["benchmarking", "console"]
    level: "DEBUG"
    propagate: true

  # Keeps your main script outputting to console
  __main__:
    handlers: ["console"]
    level: "INFO"
    propagate: true

root:
  level: "WARNING"
  handlers: ["console"]